# Site settings
title: Multimodal Food Computing
subtitle: "(MM-FOOD 2025)"
description: "The inaugral International Multimedia Food Computing workshop being hosted in conjunction with ACM Multimedia 2025."
email: foodcomputing.ashoka@gmail.com
url: "https://mm-food.github.io"
logo : "/assets/images/mm-food_logo.png"


minimal_mistakes_skin: sunrise
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
timezone:	Asia/Calcutta

include:
  - _pages

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name   : "1st International Workshop on Multimodal Food Computing"
  avatar : "/assets/images/acmmm_logo.png"
  bio    : "in conjunction with the 33rd ACM International Conference on Multimedia (ACMMM25), Dublin, Ireland, 27-31 October, 2025"
  links:
    - label: "ACM MM 2025 Workshops"
      icon: "fas fa-fw fa-link"
      url: "https://acmmm2025.org/workshop/"
    - label: "@acm_2025"
      icon: fa-brands fa-square-x-twitter
      url: "https://x.com/acm_2025"


footer:

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
