# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# Site settings
title: Multi-modal Food Computing
subtitle: "MMFood'25"
description: "The inaugral International Multimedia Food Computing workshop being hosted in conjunction with ACM Multimedia 2025."
email: mmfood.contact@gmail.com
url: "https://mm-food.github.io"
logo : "/assets/images/logo/mm-food_logo.png"


minimal_mistakes_skin: contrast # "air", "aqua", "sunrise", "dark", "dirt", "neon", "mint", "plum", "default"
search: false

google:
  search_within_pages: true
  search_engine_id: 514131c892b8a4808

# Site Settings
locale: "en-US"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
timezone:	Asia/Calcutta

include:
  - _pages

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name   : "1st International Workshop on Multi-modal Food Computing <br> (MMFood'25)"
  avatar : "/assets/images/logo/acmmm_logo2.jpg"
  date: "27/28 October, 2025"
  location : "Dublin, Ireland"
  bio    : "in conjunction with the 33rd ACM International Conference on Multimedia (ACMMM25)"
  links:
    - label: "ACM MM 2025"
      icon: "fas fa-fw fa-link"
      url: "https://acmmm2025.org/"
    - label: "mmfood.contact@gmail.com"
      icon: "fas fa-envelope"
      url: "mailto:mmfood.contact@gmail.com"

sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."


footer:

# Disable feed links
atom_feed:
  hide: true

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      author_profile: true
      classes: wide
      toc: true
      toc_sticky: true
      toc_label: "Jump To"
      toc_icon: "cogs"